# frozen_string_literal: true

require "fileutils"

module BetterAuth
  module Migration
    module SQL
      DEFAULT_MIGRATIONS_PATH = "db/better_auth/migrate"
      MISSING_MIGRATIONS_TABLE_MESSAGES = [
        /no such table/i,
        /relation .* does not exist/i,
        /table .* doesn't exist/i,
        /undefined table/i,
        /invalid object name/i
      ].freeze

      class UnsupportedAdapterError < StandardError; end

      module_function

      def render(options, dialect:, source: "better_auth")
        dialect = normalize_dialect(dialect)
        config = configuration_for(options)
        statements = BetterAuth::Schema::SQL.create_statements(config, dialect: dialect)
        [
          "-- Generated by #{source}",
          "-- Dialect: #{dialect}",
          "",
          statements.join("\n\n"),
          ""
        ].join("\n")
      end

      def generate(options, dialect:, migrations_path: DEFAULT_MIGRATIONS_PATH, timestamp: Time.now.utc.strftime("%Y%m%d%H%M%S"), source: "better_auth")
        dialect = normalize_dialect(dialect)
        FileUtils.mkdir_p(migrations_path)
        path = File.join(migrations_path, "#{timestamp}_create_better_auth_tables.sql")
        return path if File.exist?(path)

        File.write(path, render(options, dialect: dialect, source: source))
        path
      end

      def migrate(auth_or_options, migrations_path: DEFAULT_MIGRATIONS_PATH, package_name: "better_auth")
        auth = auth_for(auth_or_options)
        adapter = auth.context.adapter
        unless adapter.respond_to?(:dialect) && adapter.respond_to?(:connection)
          raise UnsupportedAdapterError, "#{package_name} migrations require core SQL adapters with connection and dialect support"
        end

        connection = adapter.connection
        dialect = normalize_dialect(adapter.dialect)
        files = Dir[File.join(migrations_path, "*.sql")].sort
        ensure_schema_migrations!(connection, dialect)
        applied = applied_migrations(connection, dialect)

        files.reject { |file| applied.include?(File.basename(file)) }.each do |file|
          execute_sql(connection, File.read(file))
          record_migration(connection, dialect, File.basename(file))
        end
      end

      def configuration_for(options)
        return options.options if options.is_a?(BetterAuth::Auth)
        return options if options.is_a?(BetterAuth::Configuration)

        BetterAuth::Configuration.new(options)
      end

      def auth_for(value)
        return value if value.is_a?(BetterAuth::Auth)

        BetterAuth.auth(value)
      end

      def ensure_schema_migrations!(connection, dialect)
        sql = case dialect
        when :postgres, :sqlite
          %(CREATE TABLE IF NOT EXISTS #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)} text PRIMARY KEY);)
        when :mysql
          %(CREATE TABLE IF NOT EXISTS #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)} varchar(191) PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;)
        when :mssql
          %(IF OBJECT_ID(N'#{quote("better_auth_schema_migrations", dialect)}', N'U') IS NULL CREATE TABLE #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)} varchar(255) PRIMARY KEY);)
        else
          raise UnsupportedAdapterError, "Unsupported SQL dialect: #{dialect}"
        end
        execute_sql(connection, sql)
      end

      def applied_migrations(connection, dialect)
        rows = execute_sql(connection, "SELECT #{quote("version", dialect)} FROM #{quote("better_auth_schema_migrations", dialect)};")
        Array(rows).map { |row| row["version"] || row[:version] }
      rescue UnsupportedAdapterError
        raise
      rescue => error
        raise error unless missing_schema_migrations_table?(error)

        []
      end

      def record_migration(connection, dialect, version)
        sql = "INSERT INTO #{quote("better_auth_schema_migrations", dialect)} (#{quote("version", dialect)}) VALUES (#{literal(version)});"
        execute_sql(connection, sql)
      end

      def execute_sql(connection, sql)
        statements(sql).each_with_object([]) do |statement, results|
          result =
            if connection.respond_to?(:exec)
              connection.exec(statement)
            elsif connection.respond_to?(:execute)
              connection.execute(statement)
            elsif connection.respond_to?(:query)
              connection.query(statement)
            else
              raise UnsupportedAdapterError, "SQL connection does not support exec, execute, or query"
            end
          results.concat(result.to_a) if result.respond_to?(:to_a)
        end
      end

      def statements(sql)
        normalized = sql.to_s.gsub("\r\n", "\n").strip
        return [] if normalized.empty?

        split_sql_statements(normalized)
      end

      def split_sql_statements(sql)
        output = []
        buffer = +""
        index = 0
        quote = nil
        line_comment = false
        block_comment = false
        dollar_tag = nil

        while index < sql.length
          state = {
            quote: quote,
            line_comment: line_comment,
            block_comment: block_comment,
            dollar_tag: dollar_tag
          }
          index, quote, line_comment, block_comment, dollar_tag = scan_sql_character(sql, buffer, index, state, output)
        end

        tail = buffer.strip
        output << tail unless tail.empty?
        output
      end

      def scan_sql_character(sql, buffer, index, state, output)
        char = sql[index]
        next_char = sql[index + 1]
        quote = state[:quote]
        line_comment = state[:line_comment]
        block_comment = state[:block_comment]
        dollar_tag = state[:dollar_tag]

        return scan_line_comment(buffer, index, char) + [quote, false, block_comment, dollar_tag] if line_comment && char == "\n"
        return scan_line_comment(buffer, index, char) + [quote, true, block_comment, dollar_tag] if line_comment
        return scan_block_comment(buffer, index, char, next_char, quote, line_comment, dollar_tag) if block_comment
        return scan_dollar_quote(sql, buffer, index, char, quote, line_comment, block_comment, dollar_tag) if dollar_tag
        return scan_quoted_string(sql, buffer, index, char, quote, line_comment, block_comment, dollar_tag) if quote
        return [index + 2, quote, true, block_comment, dollar_tag].tap { buffer << char << next_char } if char == "-" && next_char == "-"
        return [index + 2, quote, line_comment, true, dollar_tag].tap { buffer << char << next_char } if char == "/" && next_char == "*"

        tag = dollar_quote_tag_at(sql, index)
        return [index + tag.length, quote, line_comment, block_comment, tag].tap { buffer << tag } if tag
        return [index + 1, char, line_comment, block_comment, dollar_tag].tap { buffer << char } if char == "'" || char == "\""

        if char == ";"
          statement = buffer.strip
          output << statement unless statement.empty?
          buffer.clear
          return [index + 1, quote, line_comment, block_comment, dollar_tag]
        end

        buffer << char
        [index + 1, quote, line_comment, block_comment, dollar_tag]
      end

      def scan_line_comment(buffer, index, char)
        buffer << char
        [index + 1]
      end

      def scan_block_comment(buffer, index, char, next_char, quote, line_comment, dollar_tag)
        buffer << char
        if char == "*" && next_char == "/"
          buffer << next_char
          [index + 2, quote, line_comment, false, dollar_tag]
        else
          [index + 1, quote, line_comment, true, dollar_tag]
        end
      end

      def scan_dollar_quote(sql, buffer, index, char, quote, line_comment, block_comment, dollar_tag)
        if sql[index, dollar_tag.length] == dollar_tag
          buffer << dollar_tag
          [index + dollar_tag.length, quote, line_comment, block_comment, nil]
        else
          buffer << char
          [index + 1, quote, line_comment, block_comment, dollar_tag]
        end
      end

      def scan_quoted_string(sql, buffer, index, char, quote, line_comment, block_comment, dollar_tag)
        buffer << char
        if char == quote && sql[index + 1] == quote
          buffer << sql[index + 1]
          [index + 2, quote, line_comment, block_comment, dollar_tag]
        elsif char == quote
          [index + 1, nil, line_comment, block_comment, dollar_tag]
        else
          [index + 1, quote, line_comment, block_comment, dollar_tag]
        end
      end

      def dollar_quote_tag_at(sql, index)
        match = sql[index..]&.match(/\A\$[A-Za-z_][A-Za-z0-9_]*\$|\A\$\$/)
        match&.[](0)
      end

      def missing_schema_migrations_table?(error)
        message = error.message.to_s
        MISSING_MIGRATIONS_TABLE_MESSAGES.any? { |pattern| message.match?(pattern) }
      end

      def quote(identifier, dialect)
        BetterAuth::Schema::SQL.quote(identifier, dialect)
      end

      def literal(value)
        "'#{value.to_s.gsub("'", "''")}'"
      end

      def normalize_dialect(value)
        dialect = case value.to_s.downcase
        when "postgresql"
          :postgres
        when "sqlite3"
          :sqlite
        else
          value.to_sym
        end
        return dialect if [:postgres, :sqlite, :mysql, :mssql].include?(dialect)

        raise UnsupportedAdapterError, "Unsupported SQL dialect: #{dialect}"
      end
    end
  end
end
