# frozen_string_literal: true

source "https://rubygems.org"

ruby file: "../../packages/better_auth/.ruby-version"

gem "better_auth", path: "../../packages/better_auth"
gem "better_auth-api-key", path: "../../packages/better_auth-api-key"
gem "better_auth-mongodb", path: "../../packages/better_auth-mongodb"
gem "better_auth-oauth-provider", path: "../../packages/better_auth-oauth-provider"
gem "better_auth-passkey", path: "../../packages/better_auth-passkey"
gem "better_auth-redis-storage", path: "../../packages/better_auth-redis-storage"
gem "better_auth-roda", path: "../../packages/better_auth-roda"
gem "better_auth-scim", path: "../../packages/better_auth-scim"
gem "better_auth-sso", path: "../../packages/better_auth-sso"
gem "better_auth-stripe", path: "../../packages/better_auth-stripe"

gem "puma"
gem "rackup"
gem "roda"

gem "mongo"
gem "mysql2", "~> 0.5"
gem "pg", "~> 1.5"
gem "redis"
gem "sequel", "~> 5.83"
gem "sqlite3", "~> 2.0"
gem "tiny_tds", "~> 2.1"
