# frozen_string_literal: true

require_relative "better_auth/version"
require_relative "better_auth/core"
require_relative "better_auth/error"
require_relative "better_auth/api_error"
require_relative "better_auth/env"
require_relative "better_auth/secret_config"
require_relative "better_auth/crypto"
require_relative "better_auth/host"
require_relative "better_auth/url_helpers"
require_relative "better_auth/request_state"
require_relative "better_auth/response"
require_relative "better_auth/async"
require_relative "better_auth/deprecate"
require_relative "better_auth/logger"
require_relative "better_auth/instrumentation"
require_relative "better_auth/http_client"
require_relative "better_auth/oauth2"
require_relative "better_auth/password"
require_relative "better_auth/plugin"
require_relative "better_auth/configuration"
require_relative "better_auth/schema"
require_relative "better_auth/schema/sql"
require_relative "better_auth/migration_plan"
require_relative "better_auth/doctor"
require_relative "better_auth/adapters/base"
require_relative "better_auth/adapters/join_support"
require_relative "better_auth/adapters/memory"
require_relative "better_auth/adapters/sql"
require_relative "better_auth/adapters/postgres"
require_relative "better_auth/adapters/mysql"
require_relative "better_auth/adapters/sqlite"
require_relative "better_auth/adapters/mssql"
require_relative "better_auth/database_hooks"
require_relative "better_auth/adapters/internal_adapter"
require_relative "better_auth/context"
require_relative "better_auth/plugin_context"
require_relative "better_auth/plugin_registry"
require_relative "better_auth/plugins"
require_relative "better_auth/plugins/additional_fields"
require_relative "better_auth/plugins/custom_session"
require_relative "better_auth/plugins/multi_session"
require_relative "better_auth/plugins/last_login_method"
require_relative "better_auth/plugins/bearer"
require_relative "better_auth/plugins/jwt"
require_relative "better_auth/plugins/open_api"
require_relative "better_auth/plugins/access"
require_relative "better_auth/plugins/username"
require_relative "better_auth/plugins/anonymous"
require_relative "better_auth/plugins/magic_link"
require_relative "better_auth/plugins/email_otp"
require_relative "better_auth/plugins/phone_number"
require_relative "better_auth/plugins/one_time_token"
require_relative "better_auth/plugins/one_tap"
require_relative "better_auth/plugins/siwe"
require_relative "better_auth/plugins/generic_oauth"
require_relative "better_auth/plugins/dub"
require_relative "better_auth/plugins/oauth_proxy"
require_relative "better_auth/plugins/passkey"
require_relative "better_auth/plugins/organization/schema"
require_relative "better_auth/plugins/organization"
require_relative "better_auth/plugins/admin/schema"
require_relative "better_auth/plugins/admin"
require_relative "better_auth/plugins/oauth_protocol"
require_relative "better_auth/plugins/oidc_provider"
require_relative "better_auth/plugins/oauth_provider"
require_relative "better_auth/plugins/device_authorization"
require_relative "better_auth/plugins/mcp"
require_relative "better_auth/plugins/two_factor"
require_relative "better_auth/plugins/captcha"
require_relative "better_auth/plugins/have_i_been_pwned"
require_relative "better_auth/plugins/api_key"
require_relative "better_auth/plugins/sso"
require_relative "better_auth/plugins/scim"
require_relative "better_auth/social_providers"
%w[
  better_auth/plugins/stripe
  better_auth/plugins/expo
].each do |optional_plugin|
  require_relative optional_plugin if File.file?(File.expand_path("#{optional_plugin}.rb", __dir__))
end
require_relative "better_auth/session_store"
require_relative "better_auth/cookies"
require_relative "better_auth/session"
require_relative "better_auth/endpoint"
require_relative "better_auth/routes/validation"
require_relative "better_auth/routes/ok"
require_relative "better_auth/routes/error"
require_relative "better_auth/routes/sign_up"
require_relative "better_auth/routes/sign_in"
require_relative "better_auth/routes/sign_out"
require_relative "better_auth/routes/session"
require_relative "better_auth/routes/password"
require_relative "better_auth/routes/email_verification"
require_relative "better_auth/routes/user"
require_relative "better_auth/routes/account"
require_relative "better_auth/routes/social"
require_relative "better_auth/api"
require_relative "better_auth/rate_limiter"
require_relative "better_auth/request_ip"
require_relative "better_auth/middleware/origin_check"
require_relative "better_auth/router"
require_relative "better_auth/auth"

module BetterAuth
  def self.auth(options = {})
    Auth.new(options)
  end
end
