# frozen_string_literal: true

require "rake"
require_relative "../../spec_helper"

class BetterAuthRodaFakeSQLAdapter < BetterAuth::Adapters::Base
  attr_reader :connection, :dialect

  def initialize(options, connection)
    super(options)
    @connection = connection
    @dialect = :postgres
  end
end

class BetterAuthRodaFakeSQLConnection
  attr_reader :executed_statements, :applied_versions

  def initialize
    @executed_statements = []
    @applied_versions = []
  end

  def exec(statement)
    @executed_statements << statement

    if statement.match?(/SELECT .*better_auth_schema_migrations/i)
      applied_versions.map { |version| {"version" => version} }
    elsif (match = statement.match(/VALUES \('([^']+)'\)/))
      @applied_versions << match[1]
      []
    else
      []
    end
  end
end

RSpec.describe BetterAuth::Roda::Migration do
  after do
    BetterAuth::Roda.reset! if BetterAuth::Roda.respond_to?(:reset!)
  end

  it "renders core SQL migrations including plugin schemas" do
    plugin = BetterAuth::Plugin.new(
      id: "api-key-test",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            id: {type: "string", required: true},
            userId: {type: "string", required: true, references: {model: "user", field: "id"}, index: true},
            key: {type: "string", required: true, unique: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: secret, database: :memory, plugins: [plugin])

    sql = described_class.render(config, dialect: :postgres)

    expect(sql).to include("-- Generated by better_auth-roda")
    expect(sql).to include('CREATE TABLE IF NOT EXISTS "users"')
    expect(sql).to include('CREATE TABLE IF NOT EXISTS "api_keys"')
  end

  it "executes every statement in pending SQL migrations only once" do
    Dir.mktmpdir("better-auth-roda-migrate") do |dir|
      migrations_path = File.join(dir, "db/better_auth/migrate")
      FileUtils.mkdir_p(migrations_path)
      File.write(
        File.join(migrations_path, "20260427000000_create_better_auth_tables.sql"),
        "CREATE TABLE users (id text PRIMARY KEY);\nCREATE INDEX index_users_on_email ON users (email);\n"
      )
      connection = BetterAuthRodaFakeSQLConnection.new
      auth = BetterAuth.auth(
        secret: secret,
        database: ->(options) { BetterAuthRodaFakeSQLAdapter.new(options, connection) }
      )

      described_class.migrate(auth, migrations_path: migrations_path)
      described_class.migrate(auth, migrations_path: migrations_path)

      expect(connection.executed_statements.count("CREATE TABLE users (id text PRIMARY KEY)")).to eq(1)
      expect(connection.executed_statements.count("CREATE INDEX index_users_on_email ON users (email)")).to eq(1)
      expect(connection.applied_versions).to eq(["20260427000000_create_better_auth_tables.sql"])
    end
  end

  it "installs config and generates a SQL migration through Rake tasks" do
    Dir.mktmpdir("better-auth-roda-tasks") do |dir|
      in_directory(dir) do
        load_tasks

        Rake::Task["better_auth:install"].invoke
        Rake::Task["better_auth:generate:migration"].invoke

        expect(File.read("config/better_auth.rb")).to include("BetterAuth::Roda.configure")
        migrations = Dir["db/better_auth/migrate/*_create_better_auth_tables.sql"]
        expect(migrations.length).to eq(1)
        expect(File.read(migrations.first)).to include("-- Generated by better_auth-roda")
      end
    end
  ensure
    Rake.application = Rake::Application.new
  end

  it "uses BETTER_AUTH_DATABASE_DIALECT when generating migrations" do
    with_env("BETTER_AUTH_DIALECT" => nil, "BETTER_AUTH_DATABASE_DIALECT" => "sqlite") do
      Dir.mktmpdir("better-auth-roda-tasks") do |dir|
        in_directory(dir) do
          load_tasks
          write_minimal_config

          Rake::Task["better_auth:generate:migration"].invoke

          migration = Dir["db/better_auth/migrate/*_create_better_auth_tables.sql"].first
          expect(File.read(migration)).to include("-- Dialect: sqlite")
        end
      end
    end
  ensure
    Rake.application = Rake::Application.new
  end

  it "raises unsupported adapter errors through the migrate Rake task" do
    Dir.mktmpdir("better-auth-roda-tasks") do |dir|
      in_directory(dir) do
        load_tasks
        write_minimal_config

        expect {
          Rake::Task["better_auth:migrate"].invoke
        }.to raise_error(BetterAuth::Roda::Migration::UnsupportedAdapterError, /SQL adapters/)
      end
    end
  ensure
    Rake.application = Rake::Application.new
  end

  it "prints mount and documentation guidance from the routes task" do
    Dir.mktmpdir("better-auth-roda-tasks") do |dir|
      in_directory(dir) do
        load_tasks
        FileUtils.mkdir_p("config")
        File.write(
          "config/better_auth.rb",
          <<~RUBY
            BetterAuth::Roda.configure do |config|
              config.base_path = "/auth"
            end
          RUBY
        )

        expect {
          Rake::Task["better_auth:routes"].invoke
        }.to output(/\/auth\/\* -> BetterAuth.auth.*OpenAPI/m).to_stdout
      end
    end
  ensure
    Rake.application = Rake::Application.new
  end

  def secret
    "roda-secret-that-is-long-enough-for-validation"
  end

  def in_directory(path)
    previous = Dir.pwd
    Dir.chdir(path)
    yield
  ensure
    Dir.chdir(previous)
  end

  def load_tasks
    Rake.application = Rake::Application.new
    load File.expand_path("../../../lib/better_auth/roda/tasks.rb", __dir__)
  end

  def write_minimal_config(path = "config/better_auth.rb")
    FileUtils.mkdir_p(File.dirname(path))
    File.write(
      path,
      <<~RUBY
        BetterAuth::Roda.configure do |config|
          config.secret = #{secret.inspect}
          config.database = :memory
        end
      RUBY
    )
  end

  def with_env(values)
    previous = values.transform_values { nil }
    values.each do |key, value|
      previous[key] = ENV[key]
      value.nil? ? ENV.delete(key) : ENV[key] = value
    end
    yield
  ensure
    previous.each do |key, value|
      value.nil? ? ENV.delete(key) : ENV[key] = value
    end
  end
end
