# frozen_string_literal: true

require_relative "../../test_helper"
require "better_auth/sql_migration"
require "sqlite3"

class BetterAuthMigrationSQLTest < Minitest::Test
  SECRET = "test-secret-that-is-long-enough-for-validation"

  class FakeSQLAdapter < BetterAuth::Adapters::Base
    attr_reader :connection, :dialect

    def initialize(options, connection)
      super(options)
      @connection = connection
      @dialect = :postgres
    end
  end

  class FakeSQLConnection
    attr_reader :executed_statements, :applied_versions

    def initialize(select_error: nil)
      @executed_statements = []
      @applied_versions = []
      @select_error = select_error
    end

    def exec(statement)
      @executed_statements << statement

      if statement.match?(/SELECT .*better_auth_schema_migrations/i)
        raise @select_error if @select_error

        applied_versions.map { |version| {"version" => version} }
      elsif (match = statement.match(/VALUES \('([^']+)'\)/))
        @applied_versions << match[1]
        []
      else
        []
      end
    end
  end

  def test_renders_sql_migration_with_plugin_schema
    plugin = BetterAuth::Plugin.new(
      id: "api-key-test",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            id: {type: "string", required: true},
            userId: {type: "string", required: true, references: {model: "user", field: "id"}, index: true},
            key: {type: "string", required: true, unique: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory, plugins: [plugin])

    sql = BetterAuth::SQLMigration.render(config, dialect: :postgres, generator: "better_auth-test")

    assert_includes sql, "-- Generated by better_auth-test"
    assert_includes sql, "-- Dialect: postgres"
    assert_includes sql, 'CREATE TABLE IF NOT EXISTS "users"'
    assert_includes sql, 'CREATE TABLE IF NOT EXISTS "api_keys"'
  end

  def test_executes_pending_sql_migrations_once
    Dir.mktmpdir("better-auth-core-migrate") do |dir|
      migrations_path = File.join(dir, "db/better_auth/migrate")
      FileUtils.mkdir_p(migrations_path)
      File.write(
        File.join(migrations_path, "20260427000000_create_better_auth_tables.sql"),
        "CREATE TABLE users (id text PRIMARY KEY);\nCREATE INDEX index_users_on_email ON users (email);\n"
      )
      connection = FakeSQLConnection.new
      auth = BetterAuth.auth(
        secret: SECRET,
        database: ->(options) { FakeSQLAdapter.new(options, connection) }
      )

      BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)
      BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)

      assert_equal 1, connection.executed_statements.count("CREATE TABLE users (id text PRIMARY KEY)")
      assert_equal 1, connection.executed_statements.count("CREATE INDEX index_users_on_email ON users (email)")
      assert_equal ["20260427000000_create_better_auth_tables.sql"], connection.applied_versions
    end
  end

  def test_plans_all_tables_for_empty_database
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)

    assert_equal %w[users sessions accounts verifications], plan.to_create.map(&:table_name)
    assert_empty plan.to_add
    assert_empty plan.warnings
  end

  def test_plans_only_missing_additional_fields_and_indexes_for_existing_tables
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    base_config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)
    BetterAuth::SQLMigration.execute_sql(
      connection,
      BetterAuth::Schema::SQL.create_statements(base_config, dialect: :sqlite).join("\n")
    )
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      user: {
        additional_fields: {
          role: {type: "string", required: false, index: true}
        }
      }
    )

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)
    sql = BetterAuth::SQLMigration.render_pending(config, connection: connection, dialect: :sqlite, generator: "better_auth-test")

    assert_empty plan.to_create
    assert_equal ["users"], plan.to_add.map(&:table_name)
    assert_equal ["role"], plan.to_add.first.fields.keys
    assert_equal ["index_users_on_role"], plan.to_index.map(&:name)
    assert_includes sql, 'ALTER TABLE "users" ADD COLUMN "role" text'
    assert_includes sql, 'CREATE INDEX IF NOT EXISTS "index_users_on_role" ON "users" ("role")'
    refute_includes sql, 'CREATE TABLE IF NOT EXISTS "users"'
  end

  def test_plans_plugin_table_after_initial_core_schema
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    base_config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)
    BetterAuth::SQLMigration.execute_sql(
      connection,
      BetterAuth::Schema::SQL.create_statements(base_config, dialect: :sqlite).join("\n")
    )
    plugin = BetterAuth::Plugin.new(
      id: "api-key-test",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            id: {type: "string", required: true},
            userId: {type: "string", required: true, references: {model: "user", field: "id"}, index: true},
            key: {type: "string", required: true, unique: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory, plugins: [plugin])

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)

    assert_equal ["api_keys"], plan.to_create.map(&:table_name)
    assert_empty plan.to_add
    assert_equal ["index_api_keys_on_user_id"], plan.to_index.map(&:name)
  end

  def test_mssql_pending_migration_preserves_filtered_unique_indexes_for_nullable_fields
    config = BetterAuth::Configuration.new(
      secret: SECRET,
      database: :memory,
      plugins: [BetterAuth::Plugins.phone_number]
    )

    plan = BetterAuth::SQLMigration.plan_from_existing(
      config,
      existing: {
        "users" => {
          name: "users",
          columns: {
            "id" => "varchar",
            "name" => "varchar",
            "email" => "varchar",
            "email_verified" => "smallint",
            "image" => "varchar",
            "created_at" => "datetime2",
            "updated_at" => "datetime2",
            "phone_number" => "varchar",
            "phone_number_verified" => "smallint"
          },
          indexes: BetterAuth::SQLMigration.empty_index_metadata
        }
      },
      dialect: :mssql
    )
    sql = BetterAuth::Schema::SQL.pending_statements(plan).join("\n")

    assert_includes sql, "CREATE UNIQUE INDEX [uniq_users_phone_number] ON [users] ([phone_number]) WHERE [phone_number] IS NOT NULL"
    refute_includes sql, "CONSTRAINT [uniq_users_phone_number] UNIQUE ([phone_number])"
  end

  def test_warns_on_type_mismatch_without_planning_destructive_alter
    connection = SQLite3::Database.new(":memory:")
    connection.results_as_hash = true
    connection.execute('CREATE TABLE "users" ("id" text PRIMARY KEY, "email" integer);')
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory)

    plan = BetterAuth::SQLMigration.plan(config, connection: connection, dialect: :sqlite)

    assert plan.warnings.any? { |warning| warning.include?("users.email") && warning.include?("string") && warning.include?("integer") }
    refute plan.to_add.any? { |change| change.table_name == "users" && change.fields.key?("email") }
  end

  def test_does_not_record_sql_file_migration_when_statement_fails
    Dir.mktmpdir("better-auth-core-migrate-failure") do |dir|
      migrations_path = File.join(dir, "db/better_auth/migrate")
      FileUtils.mkdir_p(migrations_path)
      File.write(
        File.join(migrations_path, "20260427000000_create_better_auth_tables.sql"),
        "CREATE TABLE users (id text PRIMARY KEY);\nBROKEN;\n"
      )
      connection = FakeSQLConnection.new
      def connection.exec(statement)
        raise "broken migration statement" if statement.include?("BROKEN")

        super
      end
      auth = BetterAuth.auth(
        secret: SECRET,
        database: ->(options) { FakeSQLAdapter.new(options, connection) }
      )

      assert_raises(RuntimeError) do
        BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)
      end
      assert_empty connection.applied_versions
    end
  end

  def test_does_not_split_semicolons_inside_dollar_quoted_blocks
    sql = <<~SQL
      DO $$
      BEGIN
        RAISE NOTICE 'a;b';
      END
      $$;
      CREATE TABLE audit_log (id text PRIMARY KEY);
    SQL

    assert_equal [
      "DO $$\nBEGIN\n  RAISE NOTICE 'a;b';\nEND\n$$",
      "CREATE TABLE audit_log (id text PRIMARY KEY)"
    ], BetterAuth::SQLMigration.statements(sql)
  end

  def test_normalizes_common_database_dialect_aliases
    assert_equal :postgres, BetterAuth::SQLMigration.normalize_dialect("postgresql")
    assert_equal :sqlite, BetterAuth::SQLMigration.normalize_dialect("sqlite3")
  end
end
