# frozen_string_literal: true

require_relative "../../test_helper"
require "better_auth/sql_migration"

class BetterAuthMigrationSQLTest < Minitest::Test
  SECRET = "test-secret-that-is-long-enough-for-validation"

  class FakeSQLAdapter < BetterAuth::Adapters::Base
    attr_reader :connection, :dialect

    def initialize(options, connection)
      super(options)
      @connection = connection
      @dialect = :postgres
    end
  end

  class FakeSQLConnection
    attr_reader :executed_statements, :applied_versions

    def initialize(select_error: nil)
      @executed_statements = []
      @applied_versions = []
      @select_error = select_error
    end

    def exec(statement)
      @executed_statements << statement

      if statement.match?(/SELECT .*better_auth_schema_migrations/i)
        raise @select_error if @select_error

        applied_versions.map { |version| {"version" => version} }
      elsif (match = statement.match(/VALUES \('([^']+)'\)/))
        @applied_versions << match[1]
        []
      else
        []
      end
    end
  end

  def test_renders_sql_migration_with_plugin_schema
    plugin = BetterAuth::Plugin.new(
      id: "api-key-test",
      schema: {
        apiKey: {
          model_name: "api_keys",
          fields: {
            id: {type: "string", required: true},
            userId: {type: "string", required: true, references: {model: "user", field: "id"}, index: true},
            key: {type: "string", required: true, unique: true}
          }
        }
      }
    )
    config = BetterAuth::Configuration.new(secret: SECRET, database: :memory, plugins: [plugin])

    sql = BetterAuth::SQLMigration.render(config, dialect: :postgres, generator: "better_auth-test")

    assert_includes sql, "-- Generated by better_auth-test"
    assert_includes sql, "-- Dialect: postgres"
    assert_includes sql, 'CREATE TABLE IF NOT EXISTS "users"'
    assert_includes sql, 'CREATE TABLE IF NOT EXISTS "api_keys"'
  end

  def test_executes_pending_sql_migrations_once
    Dir.mktmpdir("better-auth-core-migrate") do |dir|
      migrations_path = File.join(dir, "db/better_auth/migrate")
      FileUtils.mkdir_p(migrations_path)
      File.write(
        File.join(migrations_path, "20260427000000_create_better_auth_tables.sql"),
        "CREATE TABLE users (id text PRIMARY KEY);\nCREATE INDEX index_users_on_email ON users (email);\n"
      )
      connection = FakeSQLConnection.new
      auth = BetterAuth.auth(
        secret: SECRET,
        database: ->(options) { FakeSQLAdapter.new(options, connection) }
      )

      BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)
      BetterAuth::SQLMigration.migrate(auth, migrations_path: migrations_path)

      assert_equal 1, connection.executed_statements.count("CREATE TABLE users (id text PRIMARY KEY)")
      assert_equal 1, connection.executed_statements.count("CREATE INDEX index_users_on_email ON users (email)")
      assert_equal ["20260427000000_create_better_auth_tables.sql"], connection.applied_versions
    end
  end

  def test_does_not_split_semicolons_inside_dollar_quoted_blocks
    sql = <<~SQL
      DO $$
      BEGIN
        RAISE NOTICE 'a;b';
      END
      $$;
      CREATE TABLE audit_log (id text PRIMARY KEY);
    SQL

    assert_equal [
      "DO $$\nBEGIN\n  RAISE NOTICE 'a;b';\nEND\n$$",
      "CREATE TABLE audit_log (id text PRIMARY KEY)"
    ], BetterAuth::SQLMigration.statements(sql)
  end

  def test_normalizes_common_database_dialect_aliases
    assert_equal :postgres, BetterAuth::SQLMigration.normalize_dialect("postgresql")
    assert_equal :sqlite, BetterAuth::SQLMigration.normalize_dialect("sqlite3")
  end
end
